### PR TITLE
Initial ideas for overlay refactor

### PR DESCRIPTION
**Pull request by richagadgil**
Ideas for Refactor:

- Each overlay has only one interaction type
- Create system of inherited types 

Addresses Issues #8 and #11

### CODE REVIEW

**Comment by Waidhoferj** [comment]
We may want to consider a `MultiActionOveraly` for UI elements that may include multiple actions (e.g. a teacher's office modal might have a link to their website and a teleport button that takes you to their classroom).

**Comment by Waidhoferj** [comment]
Also, I noticed Jason and Kalen working on a setup that mapped the JSON directly to React components. This could be a more streamlined way to present the overlays on the screen. Something like this:

```
overlays.map(overlay => {
switch(overlay.type)
    case "path":
           return <PathOverlay {...overlay}/>
    case "teleport":
           return <TeleportOverlay {...overlay}/>
   ...........
}
```

**Comment by thegooman** [comment]
@Waidhoferj can we make the assumption that every overlay has a `title` and `description`? And then render an `OverlayInteractions` component which is an array of buttons each having their own action (showing more info, traveling, etc.). Then, we would render an `Overlay` every time and render any `interactions` available within it.

Names are arbitrary, I just added them to provide context.

**Comment by Waidhoferj** [comment]
@kgoo124 I really like that idea.

**Comment by thegooman** [comment]
Decided to go with a different design pattern, new PR is #14

**Pull request closed without merging**
