### PR TITLE
Convert to Typescript

### LINKED ISSUE #15: Switch to TypeScript
We want to switch to Typescript to keep the code readable and prevent future bugs in the long run.

### PR DESCRIPTION
**Pull request by thegooman**
Closes #15

### CODE REVIEW

**Comment by thegooman** [comment]
@Waidhoferj not too sure why the netlify checks aren't working

**Comment by Waidhoferj** [comment]
Screen Shot 2021-04-12 at 10 01 31 AM
@kgoo124 If the React linting in CRA doesn't pass, it'll fail in a production build. If you correct this, it should deploy

**Comment by thegooman** [comment]
@Waidhoferj okay fixed, can you give it a look?

**Review by Waidhoferj — APPROVED** [review]
LGTM

**Pull request merged**
