### PR TITLE
Initial overlays with json refactor

### LINKED ISSUE #11: Improve overlay/interaction schema
Right now we have overlays and overlay types - instead, we can more clearly represent the relationship between overlays and the actions they perform when clicked with overlays and "interactions".

An overlay should have an array of interactions, each of which has its on jsx component.

(At least, that's what we're thinking?)

EX:
```
"overlays": [
          {
            "overlay_id": 1,
            "overlay_type": "SHOWINFO",
            "title": "What is this?",
            "description": "Truck info overlay",
            "position": [9, 5, 3],
            "args": {
              "information": "Your mom. Just kidding, it's a truck."
            }
          },
```

into:

```
"overlays": [
          {
            "overlay_id": 1,
            "title": "What is this?",
            "description": "Truck info overlay",
            "position": [9, 5, 3],
            "interactions": [
              {
                "interaction_type": SHOWINFO,
                "information": "pingu truck"
              }
            ]
          },
```

### PR DESCRIPTION
**Pull request by thegooman**
Refactored our JSON structure as mentioned #11. See sample JSON at the bottom. `Overlay` components now render an `OverlayInteractions` component that renders buttons for each `Interaction`. Still need to handle the `onClick` for every button.

```
"overlays": [
          {
            "overlay_id": 1,
            "title": "What is this?",
            "description": "Truck info overlay",
            "position": [9, 5, 3],
            "interactions": [
              {
                "interaction_type": "SHOWINFO",
                "button_text": "What is this?",
                "information": "Your mom. Just kidding, it's a truck."
              },
              {
                "interaction_type": "LINK",
                "button_text": "Go Google it",
                "url": "htttps://google.com"
              }
            ]
          },
          {
            "overlay_id": 2,
            "title": "To Tree",
            "position": [9, 3, 0],
            "interactions": [
              {
                "interaction_type": "TRAVERSE",
                "button_text": "Go to tree",
                "destination_id": 2,
                "video": "porch_tree.mp4"
              }
            ]
          }
        ]
```

Closes #11

### CODE REVIEW

**Comment by thegooman** [comment]
@Waidhoferj would you be able to work on the styling for the overlays and interaction buttons? the css variable should already be defined, you just need to modify it. thanks!

**Comment by Waidhoferj** [comment]
@kgoo124 Do you want me to push to this branch?

**Comment by thegooman** [comment]
@Waidhoferj go ahead and push to this branch

**Comment by Waidhoferj** [comment]
@kgoo124 You're good to go. I set up the logic to have the icons match the `interaction_type`, but you'll have to update your graph schema before it will work.

**Comment by thegooman** [comment]
Okay ready for merge. @Jason-Ku @Waidhoferj go ahead, review and approve if everything looks good

**Review by Jason-Ku — APPROVED** [review]
Lets merge soon!

**Review by Waidhoferj — APPROVED** [review]
Go for it

**Pull request merged**
